export const ADMIN = {
    FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
    FETCH_PRODUCTS_FAILED: 'FETCH_PRODUCTS_FAILED',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCTS_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCTS_SUCCESS',
    DELETE_PRODUCT_FAILED: 'DELETE_PRODUCTS_FAILED',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILED: 'CREATE_PRODUCT_FAILED',
    CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
    FETCH_PRODUCT_REQUEST: 'FETCH_PRODUCT_REQUEST',
    FETCH_PRODUCT_FAILED: 'FETCH_PRODUCT_FAILED',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    
}