export const COMMON = {
  FETCH_BOOKED_DETAILS_REQUEST: "FETCH_BOOKED_DETAILS_REQUEST",
  FETCH_BOOKED_DETAILS_FAILED: "FETCH_BOOKED_DETAILS_FAILED",
  FETCH_BOOKED_DETAILS_SUCCESS: "FETCH_BOOKED_DETAILS_SUCCESS",
};
